name: 'AHQ Store Upload app'
description: 'Upload your app to the AHQ Store apps repo at @ahqstore/apps'
author: '@ahqstore'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'grid'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  release:
    description: 'The release_id of the GitHub Action'
    required: true

  upload:
    description: 'Shall we upload to the AHQ Store apps repo?'
    required: true
    default: 'false'

runs:
  using: node20
  main: dist/index.js
