name: 'The name of your action here'
description: 'Provide a description here'
author: '@ahqstore'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  release:
    description: 'The release_id of the GitHub Action'
    required: true

  upload:
    description: 'Shall we upload to the AHQ Store apps repo?'
    required: true
    default: 'false'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
